# Generated by Django 4.1.5 on 2023-01-20 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="landlord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("landlord_name", models.CharField(max_length=100, null=True)),
                ("landlord_email", models.EmailField(max_length=254, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "state_of_origin",
                    models.CharField(
                        choices=[
                            ("Abia", "Abia"),
                            ("Adamawa", "Adamawa"),
                            ("Akwa-Ibom", "Akwa-Ibom"),
                            ("Anambra", "Anambra"),
                            ("Bauchi", "Bauchi"),
                            ("Bayelsa", "Bayelsa"),
                            ("Borno", "Borno"),
                            ("Cross-River", "Cross-River"),
                            ("Delta", "Delta"),
                            ("Ebonyi", "Ebonyi"),
                            ("Edo", "Edo"),
                            ("Ekiti", "Ekiti"),
                            ("Enugu", "Enugu"),
                            ("Gombe", "Gombe"),
                            ("Imo", "Imo"),
                            ("Jigawa", "Jigawa"),
                            ("Kaduna", "Kaduna"),
                            ("Kano", "Kano"),
                            ("Kastina", "Kastina"),
                            ("Kebbi", "Kebbi"),
                            ("Kogi", "Kogi"),
                            ("Kwara", "Kwara"),
                            ("Lagos", "Lagos"),
                            ("Nassarawa", "Nassarawa"),
                            ("Niger", "Niger"),
                            ("Ogun", "Ogun"),
                            ("Ondo", "Ondo"),
                            ("Osun", "Osun"),
                            ("Oyo", "Oyo"),
                            ("Plateau", "Plateau"),
                            ("Sokoto", "Sokoto"),
                            ("Sokoto", "Sokoto"),
                            ("Taraba", "Taraba"),
                            ("Yobe", "Yobe"),
                            ("Zamfara", "Zamfara"),
                            ("FCT", "FCT"),
                        ],
                        default="FCT",
                        max_length=15,
                    ),
                ),
                (
                    "date_registered",
                    models.DateField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="reg_date",
                    ),
                ),
                ("landlord_code", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="managed_properties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=60)),
                ("address", models.CharField(max_length=225, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Abia", "Abia"),
                            ("Adamawa", "Adamawa"),
                            ("Akwa-Ibom", "Akwa-Ibom"),
                            ("Anambra", "Anambra"),
                            ("Bauchi", "Bauchi"),
                            ("Bayelsa", "Bayelsa"),
                            ("Borno", "Borno"),
                            ("Cross-River", "Cross-River"),
                            ("Delta", "Delta"),
                            ("Ebonyi", "Ebonyi"),
                            ("Edo", "Edo"),
                            ("Ekiti", "Ekiti"),
                            ("Enugu", "Enugu"),
                            ("Gombe", "Gombe"),
                            ("Imo", "Imo"),
                            ("Jigawa", "Jigawa"),
                            ("Kaduna", "Kaduna"),
                            ("Kano", "Kano"),
                            ("Kastina", "Kastina"),
                            ("Kebbi", "Kebbi"),
                            ("Kogi", "Kogi"),
                            ("Kwara", "Kwara"),
                            ("Lagos", "Lagos"),
                            ("Nassarawa", "Nassarawa"),
                            ("Niger", "Niger"),
                            ("Ogun", "Ogun"),
                            ("Ondo", "Ondo"),
                            ("Osun", "Osun"),
                            ("Oyo", "Oyo"),
                            ("Plateau", "Plateau"),
                            ("Sokoto", "Sokoto"),
                            ("Sokoto", "Sokoto"),
                            ("Taraba", "Taraba"),
                            ("Yobe", "Yobe"),
                            ("Zamfara", "Zamfara"),
                            ("FCT", "FCT"),
                        ],
                        default="FCT",
                        max_length=15,
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                (
                    "date_registered",
                    models.DateField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="reg_date",
                    ),
                ),
                (
                    "property_status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Occupied"), (0, "Vacant")],
                        default=0,
                        verbose_name="Property Status",
                    ),
                ),
                ("property_code", models.CharField(max_length=30, unique=True)),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.landlord"
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(max_length=60, null=True)),
                ("tenant_email", models.EmailField(max_length=254, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Null", "_______"),
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                        ],
                        default="Null",
                        max_length=10,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Nigerian", "Nigeria"),
                            ("International", "International"),
                        ],
                        default="Nigerian",
                        max_length=50,
                    ),
                ),
                (
                    "tenant_code",
                    models.CharField(max_length=30, null=True, unique=True),
                ),
                ("next_of_kin", models.CharField(max_length=70, null=True)),
                ("nok_contact", models.CharField(blank=True, max_length=15, null=True)),
                ("occupation", models.CharField(max_length=50, null=True)),
                ("industry", models.CharField(max_length=50, null=True)),
                ("office_address", models.TextField(null=True)),
                (
                    "current_property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.managed_properties",
                        to_field="property_code",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="rentals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_use",
                    models.CharField(
                        choices=[
                            ("Residential", "Residential Purpose"),
                            ("Business", "Business Purpose"),
                        ],
                        default="Residential",
                        max_length=20,
                    ),
                ),
                (
                    "date_started",
                    models.DateField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Beginning of Rent",
                    ),
                ),
                (
                    "agreement_duration",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "6 Months"),
                            (2, "1 Year"),
                            (3, "18 Months"),
                            (4, "2 Years"),
                            (5, "3 Years"),
                            (6, "5 Years"),
                        ],
                        default=2,
                        verbose_name="agreement duration",
                    ),
                ),
                (
                    "rental_amount",
                    models.FloatField(max_length=40, verbose_name="Rental Amount"),
                ),
                (
                    "date_ending",
                    models.DateField(null=True, verbose_name="End of Rent"),
                ),
                ("agreement_code", models.CharField(max_length=30, unique=True)),
                ("remarks", models.CharField(max_length=70, null=True)),
                (
                    "balance",
                    models.FloatField(
                        max_length=40, null=True, verbose_name="Balance Outstanding"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.managed_properties",
                        to_field="property_code",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(max_length=40, verbose_name="Amount Paid"),
                ),
                ("payment_code", models.CharField(max_length=30, unique=True)),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rentals",
                        to_field="agreement_code",
                    ),
                ),
            ],
        ),
    ]
