# Generated by Django 4.1.3 on 2022-11-25 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_landlord_date_registered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlord",
            name="date_registered",
            field=models.DateField(
                default=datetime.datetime(2022, 11, 25, 9, 35, 59, 217624),
                null=True,
                verbose_name="reg_date",
            ),
        ),
        migrations.AlterField(
            model_name="managed_properties",
            name="date_registered",
            field=models.DateField(
                default=datetime.datetime(2022, 11, 25, 9, 35, 59, 218621),
                null=True,
                verbose_name="reg_date",
            ),
        ),
    ]
