# Generated by Django 4.1.3 on 2022-11-25 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_landlord_date_registered_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="spouse_full_name",
            new_name="next_of_kin",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="children",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="no_of_dependants",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="tenant_age",
        ),
        migrations.AddField(
            model_name="tenant",
            name="nok_contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tenant_code",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tenant_name",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="landlord",
            name="date_registered",
            field=models.DateField(
                default=django.utils.timezone.now, null=True, verbose_name="reg_date"
            ),
        ),
        migrations.AlterField(
            model_name="managed_properties",
            name="date_registered",
            field=models.DateField(
                default=django.utils.timezone.now, null=True, verbose_name="reg_date"
            ),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="date_started",
            field=models.DateField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Beginning of Rent",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Null", "_______"),
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                ],
                default="Null",
                max_length=10,
            ),
        ),
    ]
