# Generated by Django 4.1.3 on 2022-12-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_spouse_full_name_tenant_next_of_kin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentals",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Tenancy is Running"), (0, "Tenancy has Ended")],
                default=1,
                verbose_name="tenancy status",
            ),
        ),
        migrations.AlterField(
            model_name="managed_properties",
            name="address",
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="managed_properties",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="current_property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.managed_properties",
                to_field="property_code",
            ),
        ),
    ]
