# Generated by Django 4.1.3 on 2023-01-08 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rentals_status_alter_managed_properties_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentals",
            name="status",
        ),
        migrations.AddField(
            model_name="rentals",
            name="balance",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="rentals",
            name="remarks",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.CreateModel(
            name="payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Payment Date",
                    ),
                ),
                ("amount", models.CharField(max_length=30)),
                ("payment_code", models.CharField(max_length=30, unique=True)),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rentals",
                        to_field="agreement_code",
                    ),
                ),
            ],
        ),
    ]
