# Generated by Django 4.1.3 on 2023-01-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_rentals_status_rentals_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.FloatField(max_length=40, verbose_name="Amount Paid"),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="balance",
            field=models.FloatField(
                max_length=40, null=True, verbose_name="Balance Outstanding"
            ),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="rental_amount",
            field=models.FloatField(max_length=40, verbose_name="Rental Amount"),
        ),
    ]
